spring.application.name=demo
# --- CONEXÃO COM O BANCO DE DADOS POSTGRESQL ---
# O Spring vai procurar as variáveis de ambiente (DB_URL, DB_USER, DB_PASS).
# Se você estiver rodando no seu computador e não tiver essas variáveis, ele usa o que está depois dos dois pontos (localhost, postgres, admin).

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/livro_guarda}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURAÇÕES DO HIBERNATE / JPA ---
# O 'update' garante que o Java crie e atualize as tabelas automaticamente sem apagar os dados existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true