# Usa as variáveis de ambiente do Render, ou cai no H2 (localhost) se não achar nada
#spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
#spring.datasource.username=${DB_USER:sa}
#spring.datasource.password=${DB_PASS:}
#spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de JPA para PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# --- CONFIGURAÇÃO PADRÃO (RODA LOCAL COM H2) ---
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true